version: "3.8"

services:
  ckbfs-server:
    build:
      context: .
      target: production
    container_name: ckbfs-server-prod
    ports:
      - "6769:6759"
    environment:
      - NODE_ENV=production
      - PORT=6759
      - CKB_NETWORK=mainnet
      - LOG_LEVEL=info
      - HELMET_ENABLED=true
    restart: unless-stopped
    networks:
      - ckbfs-network

  ckbfs-server-test:
    build:
      context: .
      target: development
    container_name: ckbfs-server-test
    ports:
      - "6760:6759"
    environment:
      - NODE_ENV=test
      - PORT=6759
      - CKB_NETWORK=testnet
      - LOG_LEVEL=warn
    volumes:
      - .:/app
      - /app/node_modules
    restart: "no"
    networks:
      - ckbfs-network

networks:
  ckbfs-network:
    driver: bridge

volumes:
  node_modules:
