version: "3.8"

services:
  ckbfs-server:
    build:
      context: .
      target: production
    container_name: ckbfs-server-prod
    ports:
      - "6769:6759"
    environment:
      - NODE_ENV=production
      - PORT=6759
      - CKB_NETWORK=mainnet
      - CKB_MAINNET_URL=
      - CKB_TESTNET_URL=
      - LOG_LEVEL=info
      - HELMET_ENABLED=true
    restart: unless-stopped
    networks:
      - ckbfs-network
networks:
  ckbfs-network:
    driver: bridge

volumes:
  node_modules:
